import asyncio
import unittest
from app.conversation.engine import ConversationEngine
from app.conversation.state import ConversationState
from app.conversation.interfaces import TTSInterface, LLMInterface
from app.services.stt_service import DefaultSTTService
from app.services.rime_tts_service import RimeTTSService
from app.services.llm_service import LocalTestLLM, get_llm_service
from app.services.voice_orchestrator import VoiceOrchestrator

class MockTTSWithPlayback(TTSInterface):
    def __init__(self, delay: float = 0.2):
        self.delay = delay
        self.spoken_texts = []
        self.stop_count = 0
        self.is_playing = False

    async def speak(self, text: str) -> None:
        self.is_playing = True
        try:
            self.spoken_texts.append(text)
            await asyncio.sleep(self.delay)
        finally:
            self.is_playing = False

    async def stop(self) -> None:
        self.stop_count += 1
        self.is_playing = False


class MockSlowLLM(LLMInterface):
    def __init__(self, responses: dict = None):
        self.responses = responses or {}

    async def generate_response(self, user_input: str, history: list) -> str:
        if "Slow" in user_input:
            await asyncio.sleep(0.2)
            return "Slow LLM Response"
        return self.responses.get(user_input, f"Response to '{user_input}'")


class TestPhase3VoiceIntegration(unittest.IsolatedAsyncioTestCase):

    async def asyncSetUp(self):
        self.tts = MockTTSWithPlayback()
        self.llm = MockSlowLLM()
        self.stt = DefaultSTTService()
        self.engine = ConversationEngine(tts=self.tts, llm=self.llm, stt=self.stt)
        self.orchestrator = VoiceOrchestrator(engine=self.engine, stt=self.stt, tts=self.tts)

    # Test A — STT -> engine
    async def test_A_stt_transcript_reaches_engine(self):
        """Transcript delivered via STT triggers ConversationEngine turn creation."""
        turn = await self.orchestrator.process_user_utterance("Test STT prompt")
        self.assertIsNotNone(turn)
        self.assertEqual(turn.user_input, "Test STT prompt")
        self.assertEqual(turn.response_text, "Response to 'Test STT prompt'")

    # Test B — engine -> Rime
    async def test_B_engine_response_reaches_tts(self):
        """Valid response generated by engine reaches TTS speak()."""
        await self.orchestrator.process_user_utterance("Valid prompt")
        self.assertIn("Response to 'Valid prompt'", self.tts.spoken_texts)

    # Test C — interruption
    async def test_C_speech_start_causes_interruption_and_tts_stop(self):
        """Speech-start event while SPEAKING triggers engine interrupt and tts.stop()."""
        task_a = asyncio.create_task(self.orchestrator.process_user_utterance("Slow Question"))
        await asyncio.sleep(0.05)

        # Trigger speech start barge-in while assistant is processing/speaking
        await self.stt.simulate_speech_started()
        await task_a

        self.assertGreater(self.tts.stop_count, 0)
        self.assertEqual(self.engine.state, ConversationState.INTERRUPTED)

    # Test D — stale response
    async def test_D_stale_response_discarded_on_interruption(self):
        """Turn A response arriving after interruption is discarded."""
        task_a = asyncio.create_task(self.orchestrator.process_user_utterance("Slow Question"))
        await asyncio.sleep(0.02)

        # Interrupt and start Turn B
        await self.stt.simulate_speech_started()
        task_b = asyncio.create_task(self.orchestrator.process_user_utterance("Fast Question"))

        await asyncio.gather(task_a, task_b)

        self.assertIn("Response to 'Fast Question'", self.tts.spoken_texts)
        self.assertNotIn("Slow LLM Response", self.tts.spoken_texts)

    # Test E — new response
    async def test_E_new_turn_reaches_tts(self):
        """New turn after interruption successfully reaches TTS."""
        await self.stt.simulate_speech_started()
        turn_b = await self.orchestrator.process_user_utterance("How much pasta?")

        self.assertEqual(turn_b.user_input, "How much pasta?")
        self.assertIn("Response to 'How much pasta?'", self.tts.spoken_texts)

    # Test F — playback cancellation
    async def test_F_stopping_tts_halts_playback_task(self):
        """Calling tts.stop() sets is_playing to False."""
        self.tts.delay = 0.5
        task = asyncio.create_task(self.orchestrator.process_user_utterance("Long speech"))
        await asyncio.sleep(0.05)

        await self.tts.stop()
        self.assertFalse(self.tts.is_playing)
        await task

    # Test G — no stale audio
    async def test_G_cancelled_turn_never_invokes_playback(self):
        """Cancelled turn NEVER produces spoken audio output."""
        task_a = asyncio.create_task(self.orchestrator.process_user_utterance("Slow Question"))
        await asyncio.sleep(0.01)

        await self.engine.cancel_current_turn("Test cancellation")
        await task_a

        self.assertNotIn("Slow LLM Response", self.tts.spoken_texts)

    # Test H — LocalTestLLM produces deterministic responses
    async def test_H_local_test_llm_deterministic_responses(self):
        local_llm = LocalTestLLM()
        res_pasta = await local_llm.generate_response("How long should I cook pasta?", [])
        res_salt = await local_llm.generate_response("How much salt should I add?", [])
        res_other = await local_llm.generate_response("Random user phrase", [])

        self.assertIn("eight to twelve minutes", res_pasta)
        self.assertIn("one teaspoon of salt", res_salt)
        self.assertIn("local test response", res_other)

    # Test I — ConversationEngine works with LocalTestLLM without OpenAI API key
    async def test_I_engine_works_with_local_test_llm(self):
        local_llm = get_llm_service(provider="local")
        engine = ConversationEngine(tts=self.tts, llm=local_llm)
        turn = await engine.handle_user_input("How long should I cook pasta?")

        self.assertIsNotNone(turn)
        self.assertIn("eight to twelve minutes", turn.response_text)
        self.assertIn(turn.response_text, self.tts.spoken_texts)

    # Test J — Single transcript delivery (no duplicate turn creation)
    async def test_J_single_transcript_delivery(self):
        stt = DefaultSTTService()

        async def dummy_listen():
            return "How long to cook pasta?"

        stt.listen_and_transcribe = dummy_listen
        orchestrator = VoiceOrchestrator(engine=self.engine, stt=stt, tts=self.tts)

        turn = await orchestrator.listen_cycle()
        self.assertIsNotNone(turn)
        # Exactly one turn was processed by the engine
        self.assertEqual(self.engine.current_turn_id, turn.turn_id)


if __name__ == "__main__":
    unittest.main()
