"""Validated storage for recipes generated by an LLM."""

from typing import Any
from uuid import uuid4

from app.models.recipe import Ingredient, Recipe, RecipeStep
from app.schemas.recipe import RecipeSchema


class RecipeService:
    def __init__(self) -> None:
        self._recipes: dict[str, Recipe] = {}

    def create_recipe(self, payload: dict[str, Any]) -> Recipe:
        validated = RecipeSchema.model_validate(payload)
        recipe_id = validated.id or str(uuid4())
        recipe = Recipe(
            id=recipe_id,
            name=validated.name,
            servings=validated.servings,
            ingredients=tuple(Ingredient(**item.model_dump()) for item in validated.ingredients),
            steps=tuple(RecipeStep(**item.model_dump()) for item in validated.steps),
            version=validated.version,
        )
        self._recipes[recipe.id] = recipe
        return recipe

    def get_recipe(self, recipe_id: str) -> Recipe:
        try:
            return self._recipes[recipe_id]
        except KeyError as error:
            raise KeyError(f"unknown recipe: {recipe_id}") from error
