"""Validated storage for recipes generated by an LLM and deterministic static recipes."""

from dataclasses import dataclass
from typing import Any, List, Optional, Dict
from uuid import uuid4

from app.models.recipe import Ingredient, Recipe, RecipeStep
from app.schemas.recipe import RecipeSchema


@dataclass
class StaticRecipe:
    canonical_name: str
    aliases: List[str]
    ingredients: List[str]
    steps: List[str]


class RecipeService:
    def __init__(self) -> None:
        self._recipes: dict[str, Recipe] = {}
        self.recipes: Dict[str, StaticRecipe] = {
            "chicken pasta": StaticRecipe(
                canonical_name="Chicken Pasta",
                aliases=["chicken pasta", "chicken and pasta"],
                ingredients=[
                    "pasta",
                    "chicken",
                    "olive oil",
                    "garlic",
                    "cream",
                    "parmesan",
                    "salt",
                    "pepper",
                ],
                steps=[
                    "Bring a pot of salted water to a boil.",
                    "Cook the pasta according to package instructions, then drain.",
                    "Season the chicken with salt and pepper, then cook it in a pan with olive oil until browned.",
                    "Add minced garlic to the pan and cook for 1 minute.",
                    "Stir in the cream and parmesan cheese, simmering until thickened.",
                    "Toss the cooked pasta with the chicken and sauce. Serve hot.",
                ],
            ),
            "carbonara": StaticRecipe(
                canonical_name="Carbonara",
                aliases=["carbonara", "spaghetti carbonara", "pasta carbonara"],
                ingredients=[
                    "spaghetti",
                    "guanciale or pancetta",
                    "eggs",
                    "pecorino romano",
                    "black pepper",
                ],
                steps=[
                    "boil the spaghetti in salted water until al dente.",
                    "In a bowl, whisk together the eggs and grated pecorino cheese.",
                    "Crisp the guanciale in a large skillet over medium heat.",
                    "Transfer the pasta to the skillet with the guanciale, off the heat.",
                    "Quickly stir in the egg mixture, adding a splash of pasta water to create a creamy sauce.",
                    "Top with plenty of freshly cracked black pepper and serve.",
                ],
            ),
            "pancakes": StaticRecipe(
                canonical_name="Pancakes",
                aliases=["pancakes", "flapjacks", "hotcakes", "pancake"],
                ingredients=[
                    "flour",
                    "milk",
                    "eggs",
                    "baking powder",
                    "sugar",
                    "butter",
                    "salt",
                ],
                steps=[
                    "In a large bowl, whisk together the flour, sugar, baking powder, and a pinch of salt.",
                    "In a separate bowl, mix the milk, eggs, and melted butter.",
                    "Pour the wet ingredients into the dry ingredients and stir until just combined.",
                    "Heat a lightly oiled griddle or pan over medium-high heat.",
                    "Pour a quarter cup of batter for each pancake onto the griddle.",
                    "Brown on both sides and serve hot with syrup.",
                ],
            ),
        }

    def create_recipe(self, payload: dict[str, Any]) -> Recipe:
        validated = RecipeSchema.model_validate(payload)
        recipe_id = validated.id or str(uuid4())
        recipe = Recipe(
            id=recipe_id,
            name=validated.name,
            servings=validated.servings,
            ingredients=tuple(Ingredient(**item.model_dump()) for item in validated.ingredients),
            steps=tuple(RecipeStep(**item.model_dump()) for item in validated.steps),
            version=validated.version,
        )
        self._recipes[recipe.id] = recipe
        return recipe

    def get_recipe(self, recipe_id: str) -> Any:
        if recipe_id in self._recipes:
            return self._recipes[recipe_id]
        if recipe_id.lower() in self.recipes:
            return self.recipes[recipe_id.lower()]
        raise KeyError(f"unknown recipe: {recipe_id}")

    def find_recipe(self, user_text: str) -> Optional[StaticRecipe]:
        text = user_text.lower()
        for recipe in self.recipes.values():
            if recipe.canonical_name.lower() in text:
                return recipe
            for alias in recipe.aliases:
                if alias in text:
                    return recipe
        return None

    def get_step(self, canonical_name: str, step_index: int) -> Optional[str]:
        recipe = self.recipes.get(canonical_name.lower())
        if not recipe:
            return None
        if step_index < 0 or step_index >= len(recipe.steps):
            return None
        return recipe.steps[step_index]

    def get_total_steps(self, canonical_name: str) -> int:
        recipe = self.recipes.get(canonical_name.lower())
        if not recipe:
            return 0
        return len(recipe.steps)
